Echo "Optimizing Scheduled Tasks"
schtasks.exe /change /disable /TN "\Microsoft\Windows\.NET Framework\.NET Framework NGEN v4.0.30319 64 Critical" 
schtasks.exe /change /disable /TN "\Microsoft\Windows\.NET Framework\.NET Framework NGEN v4.0.30319 64" 
schtasks.exe /change /disable /TN "\Microsoft\Windows\.NET Framework\.NET Framework NGEN v4.0.30319 Critical" 
schtasks.exe /change /disable /TN "\Microsoft\Windows\.NET Framework\.NET Framework NGEN v4.0.30319" 
schtasks.exe /change /disable /TN "\Microsoft\Windows\Application Experience\StartupAppTask" 
schtasks.exe /change /disable /TN "\Microsoft\Windows\Autochk\Proxy" 
schtasks.exe /change /disable /TN "\Microsoft\Windows\BrokerInfrastructure\BgTaskRegistrationMaintenanceTask" 
schtasks.exe /change /disable /TN "\Microsoft\Windows\Diagnosis\Scheduled"
schtasks.exe /change /disable /TN "\Microsoft\Windows\DiskCleanup\SilentCleanup" 
schtasks.exe /change /disable /TN "\Microsoft\Windows\DiskFootprint\StorageSense" 
schtasks.exe /change /disable /TN "\Microsoft\Windows\International\Synchronize Language Settings" 
schtasks.exe /change /disable /TN "\Microsoft\Windows\SoftwareProtectionPlatform\SvcRestartTaskLogon"
schtasks.exe /change /disable /TN "\Microsoft\Windows\Time Synchronization\ForceSynchronizeTime" 
schtasks.exe /change /disable /TN "\Microsoft\Windows\Time Synchronization\SynchronizeTime" 
schtasks.exe /change /disable /TN "\Microsoft\Windows\UPnP\UPnPHostConfig" 
schtasks.exe /change /disable /TN "\Microsoft\Windows\Windows Filtering Platform\BfeOnServiceStartTypeChange" 
schtasks.exe /change /disable /TN "\Microsoft\Windows\CertificateServicesClient\AikCertEnrollTask" 
schtasks.exe /change /disable /TN "\Microsoft\Windows\CertificateServicesClient\KeyPreGenTask" 
schtasks.exe /change /disable /TN "\Microsoft\Windows\Clip\License Validation" 
schtasks.exe /change /disable /TN "\Microsoft\Windows\Defrag\ScheduledDefrag" 
schtasks.exe /change /disable /TN "\Microsoft\Windows\Device Setup\Metadata Refresh" 
schtasks.exe /change /disable /TN "\Microsoft\Windows\DiskDiagnostic\Microsoft-Windows-DiskDiagnosticDataCollector" 
schtasks.exe /change /disable /TN "\Microsoft\Windows\DiskDiagnostic\Microsoft-Windows-DiskDiagnosticResolver" 
schtasks.exe /change /disable /TN "\Microsoft\Windows\DiskFootprint\Diagnostics" 
schtasks.exe /change /disable /TN "\Microsoft\Windows\InstallService\ScanForUpdates" 
schtasks.exe /change /disable /TN "\Microsoft\Windows\InstallService\ScanForUpdatesAsUser" 
schtasks.exe /change /disable /TN "\Microsoft\Windows\InstallService\SmartRetry" 
schtasks.exe /change /disable /TN "\Microsoft\Windows\Registry\RegIdleBackup" 
schtasks.exe /change /disable /TN "\Microsoft\Windows\Security\Pwdless\IntelligentPwdlessTask" 
schtasks.exe /change /disable /TN "\Microsoft\Windows\SoftwareProtectionPlatform\SvcRestartTaskNetwork" 
schtasks.exe /change /disable /TN "\Microsoft\Windows\StateRepository\MaintenanceTasks" 
schtasks.exe /change /disable /TN "\Microsoft\Windows\Subscription\EnableLicenseAcquisition" 
schtasks.exe /change /disable /TN "\Microsoft\Windows\Subscription\LicenseAcquisition" 
schtasks.exe /change /disable /TN "\Microsoft\Windows\Sysmain\ResPriStaticDbSync" 
schtasks.exe /change /disable /TN "\Microsoft\Windows\Sysmain\WsSwapAssessmentTask" 
schtasks.exe /change /disable /TN "\Microsoft\Windows\WDI\ResolutionHost" 
schtasks.exe /change /disable /TN "\Microsoft\Windows\Windows Error Reporting\QueueReporting" 
schtasks.exe /change /disable /TN "\Microsoft\Windows\Windows Filtering Platform\BfeOnServiceStartTypeChange" 
schtasks.exe /change /disable /TN "\Microsoft\Windows\Wininet\CacheTask" 
schtasks.exe /delete /f /tn "\Microsoft\Windows\TaskScheduler" 
schtasks.exe /delete /f /tn "\Microsoft\Windows\WaaSMedic" 
schtasks.exe /delete /f /tn "\Microsoft\Windows\WindowsUpdate" 
schtasks.exe /delete /f /tn "\Microsoft\Windows\WindowsUpdate\Scheduled Start" 
schtasks.exe /delete /f /tn "\Microsoft\Windows\UpdateOrchestrator\Report policies" 
schtasks.exe /delete /f /tn "\Microsoft\Windows\UpdateOrchestrator\Schedule Scan" 
schtasks.exe /delete /f /tn "\Microsoft\Windows\UpdateOrchestrator\Schedule Scan Static Task" 
schtasks.exe /delete /f /tn "\Microsoft\Windows\UpdateOrchestrator\USO_UxBroker" 
schtasks.exe /delete /f /tn "\Microsoft\Windows\UpdateOrchestrator\Schedule Wake To Work" 
schtasks.exe /delete /f /tn "\Microsoft\Windows\UpdateOrchestrator\Start Oobe Expedite Work"